### PR TITLE
Adding a practical bounds check for ObsFilter

### PR DESCRIPTION
**Pull request by EricJames-NOAA**
## Description

The new code in PracticalBoundsCheck.cc and PracticalBoundsCheck.h adds a new simplified bounds check for observations.  It adds this new feature within UFO.

## Definition of Done

The practical bounds check code is finished and new Ctests were added.  The filter works as expected.

### CODE REVIEW

**Review by LiaofanLin-NOAA — APPROVED** [review]
nice!

**Comment by fabiolrdiniz** [comment]
Hi @EricJames-NOAA. Your `src/ufo/filters/PracticalBoundsCheck.cc` and `test/testinput/qc_practical_boundscheck.yaml` have conflicts with develop.

**Comment by fabiolrdiniz** [comment]
> Hi @EricJames-NOAA. Your `src/ufo/filters/PracticalBoundsCheck.cc` and `test/testinput/qc_practical_boundscheck.yaml` have conflicts with develop.

You can check these conflicts easily either through this web interface or from your Jupiter terminal.

**Comment by EricJames-NOAA** [comment]
> > Hi @EricJames-NOAA. Your `src/ufo/filters/PracticalBoundsCheck.cc` and `test/testinput/qc_practical_boundscheck.yaml` have conflicts with develop.
> 
> You can check these conflicts easily either through this web interface or from your Jupiter terminal.

Thank you.  I don't understand why I didn't see these conflicts when I made the pull request.  

I don't know C++ very well.  Does indentation matter?  I only see a few indentation changes in the PracticalBoundsCheck.cc conflict

**Comment by fabiolrdiniz** [comment]
> > > Hi @EricJames-NOAA. Your `src/ufo/filters/PracticalBoundsCheck.cc` and `test/testinput/qc_practical_boundscheck.yaml` have conflicts with develop.
> > 
> > 
> > You can check these conflicts easily either through this web interface or from your Jupiter terminal.
> 
> Thank you. I don't understand why I didn't see these conflicts when I made the pull request.
> 
> I don't know C++ very well. Does indentation matter? I only see a few indentation changes in the PracticalBoundsCheck.cc conflict

Yes. Something helpful for keeping the "norms" is running the `ctest` from your build directory with extra verbose activated for the `ufo_coding_norms`. You can check it with this command `ctest -VV -R ufo_coding_norms` from your build directory. It will show up the issues with the norms on the code.

**Pull request closed without merging**
