### PR TITLE
Add new Bounds check filter and test for JEDI Practical

### PR DESCRIPTION
**Pull request by orlewis**
## Description

A new filter called PracticalBoundsCheck which can filter out results which do not fall between a minimum and maximum value. There is also a test to go along with this new filter. 

## Definition of Done

This new filter will allow a user to define a bounds to data. Using a minimum and maximum the data can be bounded by these values only allowing data that lies between these values to be included. 

### Issue(s) addressed
Practical - there is no issue to be addressed 

## Dependencies
None

## Impact
None

### CODE REVIEW

**Comment by neill-b** [comment]
It's good to state "None" under Impact and Dependencies.

**Review by neill-b — APPROVED** [review]
Excellent work!

**Comment by orlewis** [comment]
Thanks I will edit the PR to state None.

**Review by JoanneAWaller — APPROVED** [review]
The PR clearly describes the code changes. The changes are concise and the test appropriate.

**Pull request closed without merging**
