### PR TITLE
Feature/new qc filter example

### PR DESCRIPTION
**Pull request by christinaholtNOAA**
## Description

This adds the changes outlined in the Wednesday A Practical Session without updated tests tests.

## Definition of Done

A merged and/or reviewed PR for Friday's practical.
### Issue(s) addressed

None available.

## Dependencies

None

## Impact

None

### CODE REVIEW

**Comment by aditya980** [comment]
#Description
Changes to code for practical

#Definition of Done
completed development followed by pull request

#Issues addressed
None

#Dependencies and Impact
NA

**Review by LiaofanLin-NOAA — APPROVED** [review]
looks good!

**Review by cshartsough — APPROVED** [review]
perhaps we could set up some color tables and add a couple new transforms?

did you pass the pylint and pytest steps?

:-)

**Comment by christinaholtNOAA** [comment]
@cshartsough I ran ALL THE TESTS! ;)

What colors would you prefer?

**Comment by cshartsough** [comment]
> @cshartsough I ran ALL THE TESTS! ;)
> 
> What colors would you prefer?

I think we should take a few colors from several different color tables and blend them.  :-)

**Comment by magnetoo** [comment]
Hey, it seems yaml file is missed? It should be 5 changed files in total, right?

**Comment by magnetoo** [comment]
It seems one more is missing, ufo/test/CMakeList Should be 6 files in total.  Any case, thank you everyone! It's been a nice week!

**Pull request closed without merging**
